/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smma.juegosTablero.gui;

import java.util.List;
import juegosTablero.Vocabulario.ModoJuego;
import static juegosTablero.Vocabulario.ModoJuego.UNICO;
import juegosTablero.Vocabulario.TipoJuego;
import smma.juegosTablero.agentes.AgenteCentralJuego;

/**
 *
 * @author pedroj
 */
public class JuegosTableroJFrame extends javax.swing.JFrame {
    private final AgenteCentralJuego agente;

    /**
     * Creates new form Consola
     * @param agente
     */
    public JuegosTableroJFrame(AgenteCentralJuego agente) {
        initComponents();
        
        this.agente = agente;
        
        this.setTitle("Juegos de Tablero de : " + agente.getLocalName());
        setVisible(true);
        proponerJuego.setEnabled(false);
        completarJuego.setEnabled(false);
        jComboBoxJuego.removeAllItems();
    }

    public void activaProponerJuego(List<TipoJuego> listaJuegos) {
        jComboBoxJuego.removeAllItems();
        for ( TipoJuego juego : listaJuegos )
            jComboBoxJuego.addItem(juego.toString());
        proponerJuego.setEnabled(true);
    }
    
    public void activaCompletarJuego() {
        completarJuego.setEnabled(true);
    }
    
    public void anulaProponerJuego() {
        jComboBoxJuego.removeAllItems();
        proponerJuego.setEnabled(false);
    }
    
    public void anulaCompletarJuego() {
        completarJuego.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proponerJuego = new javax.swing.JButton();
        completarJuego = new javax.swing.JButton();
        jComboBoxJuego = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxModo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        proponerJuego.setText("Proponer Juego");
        proponerJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proponerJuegoActionPerformed(evt);
            }
        });

        completarJuego.setText("Completar Juego");
        completarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completarJuegoActionPerformed(evt);
            }
        });

        jComboBoxJuego.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJuegoActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo Juego");

        jLabel2.setText("Modo Juego");

        jComboBoxModo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UNICO", "TORNEO" }));
        jComboBoxModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(proponerJuego)
                        .addGap(18, 18, 18)
                        .addComponent(completarJuego)
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jComboBoxJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxModo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxModo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proponerJuego)
                    .addComponent(completarJuego))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    private void completarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completarJuegoActionPerformed
        // TODO add your handling code here:
        agente.completarJuego();
    }//GEN-LAST:event_completarJuegoActionPerformed

    private void proponerJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proponerJuegoActionPerformed
        // TODO add your handling code here:
        // Proponemos un juego con los parámetros seleccionados
        ModoJuego modoJuego;
        TipoJuego tipoJuego = null;
        
        for ( TipoJuego tipo : TipoJuego.values() )
            if ( jComboBoxJuego.getSelectedItem().toString().equals(tipo.name()) ) {
                tipoJuego = tipo;
                break;
            }
        
        modoJuego = ModoJuego.values()[jComboBoxModo.getSelectedIndex()];
        
        agente.proponerJuego(tipoJuego, modoJuego);
    }//GEN-LAST:event_proponerJuegoActionPerformed

    private void jComboBoxJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJuegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxJuegoActionPerformed

    private void jComboBoxModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxModoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton completarJuego;
    private javax.swing.JComboBox<String> jComboBoxJuego;
    private javax.swing.JComboBox<String> jComboBoxModo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton proponerJuego;
    // End of variables declaration//GEN-END:variables

}
