/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smma.juegosTablero.gui;

import juegosTablero.Vocabulario.TipoJuego;
import smma.juegosTablero.agentes.AgenteCentralJuego;

/**
 *
 * @author pedroj
 */
public class JuegosTableroJFrame extends javax.swing.JFrame {
    private final AgenteCentralJuego agente;

    /**
     * Creates new form Consola
     * @param agente
     */
    public JuegosTableroJFrame(AgenteCentralJuego agente) {
        initComponents();
        
        this.agente = agente;
        
        this.setTitle("Juegos de Tablero de : " + agente.getLocalName());
        setVisible(true);
        proponerJuego.setEnabled(false);
        completarJuego.setEnabled(false);
    }

    public void activaProponerJuego() {
        proponerJuego.setEnabled(true);
    }
    
    public void activaCompletarJuego() {
        completarJuego.setEnabled(true);
    }
    
    public void anulaProponerJuego() {
        proponerJuego.setEnabled(false);
    }
    
    public void anulaCompletarJuego() {
        completarJuego.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proponerJuego = new javax.swing.JButton();
        completarJuego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        proponerJuego.setText("Proponer Juego");
        proponerJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proponerJuegoActionPerformed(evt);
            }
        });

        completarJuego.setText("Completar Juego");
        completarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completarJuegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(proponerJuego)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(completarJuego)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proponerJuego)
                    .addComponent(completarJuego))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    private void completarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completarJuegoActionPerformed
        // TODO add your handling code here:
        agente.completarJuego();
    }//GEN-LAST:event_completarJuegoActionPerformed

    private void proponerJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proponerJuegoActionPerformed
        // TODO add your handling code here:
        // Proponemos un juego aleatorio entre los posibles y donde hay jugadores
        TipoJuego tipoJuego;
        
        tipoJuego = agente.buscarJuego();
        
        agente.proponerJuego(tipoJuego);
    }//GEN-LAST:event_proponerJuegoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton completarJuego;
    private javax.swing.JButton proponerJuego;
    // End of variables declaration//GEN-END:variables

}
